module.exports = {
  VOTE_STATUS: { PENDING: "PENDING", CONFIRMED: "CONFIRMED", FAILED: "FAILED" },
  VOTER_STATUS: {
    PENDING: "PENDING",
    VERIFIED: "VERIFIED",
    REJECTED: "REJECTED",
    BLACKLISTED: "BLACKLISTED",
  },
  ELECTION_STATUS: {
    DRAFT: "DRAFT",
    ACTIVE: "ACTIVE",
    PAUSED: "PAUSED",
    CLOSED: "CLOSED",
    RESULTS_DECLARED: "RESULTS_DECLARED",
  },
  NOTIFICATION_TYPE: {
    VOTE_CONFIRMED: "VOTE_CONFIRMED",
    VERIFICATION_SUCCESS: "VERIFICATION_SUCCESS",
    FRAUD_ALERT: "FRAUD_ALERT",
    ELECTION_STARTED: "ELECTION_STARTED",
    RESULTS_DECLARED: "RESULTS_DECLARED",
  },
  DELEGATION_STATUS: {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    USED: "USED",
    EXPIRED: "EXPIRED",
    REVOKED: "REVOKED",
  },
};
